spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: postgres
    password: 123
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
      embedding:
        model: nomic-embed-text
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat: DEBUG
    org.springframework.ai.ollama: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.http: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops